apiVersion: v1
kind: Service
metadata:
  name: game-api-svc
  namespace: fiap-fcg
spec:
  selector:
    app: game-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
